services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sales_app
        restart: unless-stopped
        ports:
            - "9000:8080"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "category_db"
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: 1
        ports:
            - "8081:80"
        networks:
            - app-network

    web:
        container_name: sales_web
        image: nginx:alpine
        ports:
            - "9900:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    node:
        image: node:20
        container_name: node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        command: bash -c "npm install && npm run dev"
        ports:
            - "5173:5173"

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
